name       : plasma-framework
version    : 5.53.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/plasma-framework-5.53.0.tar.xz : d5d36826af3363a89ff76292dd0f7c8fee91a6595039b1ea6cbb05c309b09e6b
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Foundational libraries, components, and tools of the Plasma workspaces
description: |
    Foundational libraries, components, and tools of the Plasma workspaces.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - kirigami2-devel
    - knotifications-devel
    - kpackage-devel
    - kservice-devel
    - kwayland-devel
    - kwindowsystem-devel
    - kxmlgui-devel
rundeps    :
    - qt5-quickcontrols2
    - devel :
        - kpackage-devel
        - kservice-devel
        - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
