name       : plasma-framework
version    : 5.100.0
release    : 78
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.100/plasma-framework-5.100.0.tar.xz : 6476364079db3a11133608048b3b6f6b9a904083ef193ea0b3ccd0bf96c73280
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : programming.library
summary    : Foundational libraries, components, and tools of the Plasma workspaces
description: |
    Foundational libraries, components, and tools of the Plasma workspaces.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - kactivities-devel
    - karchive-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - knotifications-devel
    - kpackage-devel
    - kwayland-devel
rundeps    :
    - qt5-quickcontrols2
    - devel :
        - kpackage-devel
        - kservice-devel
        - kwindowsystem-devel
setup      : |
    %patch -p1 < $pkgfiles/do-not-upscale-svg-when-using-fractional-scaling.patch
    %cmake_ninja -DBUILD_QCH=OFF \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
