name       : plasma-framework
version    : 5.44.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/plasma-framework-5.44.0.tar.xz : bfb647e4119764872f29685ec84206e4031d9d1aaeba2a539eeec7aa5eaed9d1
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Foundational libraries, components, and tools of the Plasma workspaces
description: |
    Foundational libraries, components, and tools of the Plasma workspaces.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - kirigami2-devel
    - knotifications-devel
    - kpackage-devel
    - kservice-devel
    - kwayland-devel
    - kwindowsystem-devel
    - kxmlgui-devel
rundeps    :
    - qt5-quickcontrols2
    - devel :
        - kpackage-devel
        - kservice-devel
        - kwindowsystem-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
