name       : plasma-framework
version    : 5.35.0
release    : 2
source     :
    - https://download.kde.org/stable/frameworks/5.35/plasma-framework-5.35.0.tar.xz : 811210acaabbcc7ea7ff79f6459c35d8ec0b3decffdb52a765a0c03640cd31af
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
summary    : Foundational libraries, components, and tools of the Plasma workspaces
description: |
    Foundational libraries, components, and tools of the Plasma workspaces.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - kpackage-devel
    - kservice-devel
    - kwayland-devel
    - kwindowsystem-devel
    - kxmlgui-devel
rundeps    :
    - qt5-quickcontrols
    - devel :
        - kpackage-devel
        - kservice-devel
setup      : |
    %cmake -DBUILD_TESTING=OFF .
build      : |
    %make
install    : |
    %make_install
