name       : plasma-framework
version    : 5.39.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.39/plasma-framework-5.39.0.tar.xz : a38f92df010d063a934a04d181c30bcac40df5f0494cfc1268d453fe6b9a5dbd
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
summary    : Foundational libraries, components, and tools of the Plasma workspaces
description: |
    Foundational libraries, components, and tools of the Plasma workspaces.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - kpackage-devel
    - kservice-devel
    - kwayland-devel
    - kwindowsystem-devel
    - kxmlgui-devel
rundeps    :
    - qt5-quickcontrols2
    - devel :
        - kpackage-devel
        - kservice-devel
        - kwindowsystem-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
