name       : plasma-framework
version    : 5.70.1
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.70/plasma-framework-5.70.1.tar.xz : e28884da2e3389513d96794f71fdfa22a8b4ba62396b7d061b4f18d9b5549d19
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Foundational libraries, components, and tools of the Plasma workspaces
description: |
    Foundational libraries, components, and tools of the Plasma workspaces.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
    - karchive-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - kirigami2-devel
    - knotifications-devel
    - kwayland-devel
    - kwindowsystem-devel
rundeps    :
    - qt5-quickcontrols2
    - devel :
        - kpackage-devel
        - kservice-devel
        - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
