name       : plasma-framework
version    : 5.70.0
release    : 48
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.70/plasma-framework-5.70.0.tar.xz : 6cd229ac8ec44832c3ea83099c4b6d35ca8a8c8683b5dcdf788d225b37041f5d
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Foundational libraries, components, and tools of the Plasma workspaces
description: |
    Foundational libraries, components, and tools of the Plasma workspaces.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb)
    - extra-cmake-modules
    - karchive-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - kirigami2-devel
    - knotifications-devel
    - kwayland-devel
    - kwindowsystem-devel
rundeps    :
    - qt5-quickcontrols2
    - devel :
        - kpackage-devel
        - kservice-devel
        - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
